### ISSUE TITLE
Error on tar package

### ISSUE THREAD

**Issue by aelesbao** [Freed-Wu/tree-sitter-tmux#14]
After the `0.0.3` release, I started getting this error when installing the package on NeoVim:

```
Error opening archive: Failed to open 'tree-sitter-tmux.tar.gz'
```

I've tried to uninstall and `:TSUpdateSync tmux`, but the syntax doesn't look right:

<img width="1775" alt="Screenshot 2024-03-27 at 13 19 04" src="https://github.com/Freed-Wu/tree-sitter-tmux/assets/466801/3fbbd654-c249-40af-8b3c-b80d64233f8a">

I'm running NeoVim on macOS:

```console
$ vim -vvv                                                                                                                                                                        took 13s   13:20
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.5/share/nvim"
```

**Comment by Freed-Wu** [comment]
Works for me.

![Screenshot from 2024-03-27 22-15-35](https://github.com/Freed-Wu/tree-sitter-tmux/assets/32936898/5d398b17-4d98-4d72-9e82-bd423f9e02ac)

0.0.3 add support for `set-window-option` (`setw`) #4

**Comment by Freed-Wu** [comment]
> Error opening archive: Failed to open 'tree-sitter-tmux.tar.gz'

I think it is network error. You download a incomplete tar so it cannot be opened.

**Comment by aelesbao** [comment]
@Freed-Wu, I wanted to follow up because the issue still seems to be recurring. It resembles what was reported on #6 and #20.

Here are the parsed trees for two files:

<img width="1792" alt="Screenshot 2024-11-27 at 11 19 52" src="https://github.com/user-attachments/assets/ab12d492-4496-4b12-968f-e352ff849ce1">

<img width="1792" alt="Screenshot 2024-11-27 at 11 21 00" src="https://github.com/user-attachments/assets/3964e861-a080-441c-93b5-8919c294937b">
