### ISSUE TITLE
Noticed syntax colouring failure in `tmux.conf` in neovim using kickstarter.nvim which uses treesitter

### ISSUE THREAD

**Issue by rluiten** [Freed-Wu/tree-sitter-tmux#19]
I hope I am in the correct place for this.

To narrow down the problem I created a new neovim config from https://github.com/nvim-lua/kickstart.nvim/ totally default. Then created two example config files one which shows the error and one which does not.

The image shows that the comment line after the bind is incorrect in the file called `tmux.conf` but is correct in the file called `test.conf`. This lead me to look at kickstarter.nvim which uses treesitter which uses this tree-sitter-tmux I believe.
I assume the file `test.conf` is running some generic *.conf file syntax colouring.

![tmux syntax colour error image](https://github.com/Freed-Wu/tree-sitter-tmux/assets/670472/89170597-3975-4f65-a134-6565920bce24)

This is the content of the test files I used. I attached the file with .txt suffix as well.
```
# Smart pane switching with awareness of Neovim splits.
bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h'  'select-pane -L'
# Smart pane resizing with awareness of Neovim splits.
```
[tmux.conf.txt](https://github.com/Freed-Wu/tree-sitter-tmux/files/14967140/tmux.conf.txt)

**Comment by Freed-Wu** [comment]
Add a bracket before #2 is solved.

```tmux
# Smart pane switching with awareness of Neovim splits.
bind-key -n C-h {
  if -F "#{@pane-is-vim}" 'send-keys C-h'  'select-pane -L'
}
# Smart pane resizing with awareness of Neovim splits.
```
